#!/bin/bash
export PATH="$PATH:/opt/homebrew/bin"

filename="project.yml"
copyFileName="project_copy.yml"
generateScript="generate"
current_directory="$PWD"
projectName="Example"
targetName="Example"
projectReg="{PROJECT_NAME}"
targetReg="{TARGET_NAME}"

cp $filename $copyFileName

# Change directory to be where the command is.
cd "$(cd "$(dirname "$0")" > /dev/null && pwd)"

# Replace project and target name in project.yml
sed -i -e "s/$projectReg/$projectName/g" $filename
sed -i -e "s/$targetReg/$targetName/g" $filename

# Delete empty file with name "project.yml-e"
rm project.yml-e

# Execute sh generate script
source $current_directory/$generateScript

# rm project.yml
rm $filename

# rename copy_project.yml to project.yml
mv $copyFileName $filename
